Models/TablaTurnos.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TurneroFaeracWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TablaTurnos
    {
        public int IdTurno { get; set; }
        public int IdPaciente { get; set; }
        public Nullable<System.DateTime> Fin { get; set; }
        public Nullable<System.DateTime> inicio { get; set; }
        public string Estado { get; set; }
        public string NombrePaciente { get; set; }
        public string NombreDoc { get; set; }
        public string ApeDoc { get; set; }
        public Nullable<int> IdDia { get; set; }
        public string NombreDia { get; set; }
        public string Fecha { get; set; }
        public Nullable<int> EdadPac { get; set; }
        public Nullable<int> IdDoc { get; set; }
    
        public virtual Doctores Doctores { get; set; }
    }
}

Controllers/TablasController.cs
using Google;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Security.Claims;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using TurneroFaeracWeb.Models;


namespace FaeracT.Controllers
{
    public class TablasController : Controller
    {
        public ActionResult TablaUsuarios(UsuarioCLS oUsuarioCLS)
        {
            try
            {
                if (Session["UserID"] == null)
                {
                    return RedirectToAction("Login", "Login");
                }
                else
                {
                    string nombreUSR = oUsuarioCLS.Usuario;
                    llenarGenero();
                    GetTipoUsuarioList();
                    GetGeneroUsuarioList();
                    List<UsuarioCLS> listaUsuario = new List<UsuarioCLS>();
                    using (var db = new TurneroNewEntities())
                    {
                        if (oUsuarioCLS.Usuario == null)
                        {
                            listaUsuario = (from Usuario in db.Usuarios
                                            select new UsuarioCLS
                                            {
                                                IdUser = Usuario.IdUser,
                                                Usuario = Usuario.Usuario,
                                                Contraseña = Usuario.Contraseña,
                                                IdTipo = Usuario.IdTipo,
                                                Genero = Usuario.Genero,
                                                NumeroContacto = Usuario.NumeroContacto
                                            }).ToList();
                            Session["lista"] = listaUsuario;
                        }
                        else
                        {
                            listaUsuario = (from Usuario in db.Usuarios
                                            where Usuario.IdTipo != 4
                                            select new UsuarioCLS
                                            {
                                                IdUser = Usuario.IdUser,
                                                Usuario = Usuario.Usuario,
                                                Contraseña = Usuario.Contraseña,
                                                IdTipo = Usuario.IdTipo,
                                                Genero = Usuario.Genero,
                                                NumeroContacto = Usuario.NumeroContacto
                                            }).ToList();

                            Session["lista"] = listaUsuario;
                        }
                    }
                    return View(listaUsuario);
                }
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Home");
            }
        }

        public ActionResult TablaDoctores(DoctoresCLS oDoctoresCLS)
        {
            try
            {
                if (Session["UserID"] == null)
                {
                    return RedirectToAction("Login", "Login");
                }
                else
                {
                    llenarEspecializacion();
                    ViewBag.Lista = listaEspecializacion;
                    string apeDoc = oDoctoresCLS.ApeDoc;

                    List<DoctoresCLS> listaDocs = new List<DoctoresCLS>();
                    using (var db = new TurneroNewEntities())
                    {
                        if (oDoctoresCLS.ApeDoc == null)
                        {
                            listaDocs = (from doctores in db.Doctores
                                         select new DoctoresCLS
                                         {
                                             IdDoc = doctores.IdDoc,
                                             IdUser = doctores.IdUser,
                                             ApeDoc = doctores.ApeDoc,
                                             NombreDoc = doctores.NombreDoc,
                                             IDEspecializacion = doctores.IDEspecializacion
                                         }).ToList();
                            Session["lista"] = listaDocs;
                        }
                        else
                        {
                            listaDocs = (from doctores in db.Doctores
                                         select new DoctoresCLS
                                         {
                                             IdDoc = doctores.IdDoc,
                                             IdUser = doctores.IdUser,
                                             ApeDoc = doctores.ApeDoc,
                                             NombreDoc = doctores.NombreDoc,
                                             IDEspecializacion = doctores.IDEspecializacion
                                         }).ToList();

                            Session["lista"] = listaDocs;
                        }
                    }
                    return View(listaDocs);
                }
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Home");
            }
        }

        public ActionResult TablaPacientes(PacientesCLS oPacientesCLS)
        {
            try
            {
                if (Session["UserID"] == null)
                {
                    return RedirectToAction("Login", "Login");
                }
                else
                {
                    llenarEspecializacion();
                    ViewBag.Lista = listaEspecializacion;
                    string dnipac = oPacientesCLS.NombrePac;

                    List<PacientesCLS> listaPacs = new List<PacientesCLS>();
                    using (var db = new TurneroNewEntities())
                    {
                        if (oPacientesCLS.NombrePac == null)
                        {
                            listaPacs = (from pacientes in db.Pacientes
                                         select new PacientesCLS
                                         {
                                             IdPaciente = pacientes.IdPaciente,
                                             NombrePac = pacientes.NombrePac,
                                             ApePac = pacientes.ApePac,
                                             DNIPac = pacientes.DNIPac,
                                             TipoDNI = pacientes.TipoDNI,
                                             EdadPac = pacientes.EdadPac,
                                             Genero = pacientes.Genero,
                                             IdUser = pacientes.IdUser,
                                             Correo = pacientes.Correo,
                                             NumeroContacto = pacientes.NumeroContacto
                                         }).ToList();
                            Session["lista"] = listaPacs;
                        }
                        else
                        {
                            listaPacs = (from pacientes in db.Pacientes
                                         select new PacientesCLS
                                         {
                                             IdPaciente = pacientes.IdPaciente,
                                             NombrePac = pacientes.NombrePac,
                                             ApePac = pacientes.ApePac,
                                             DNIPac = pacientes.DNIPac,
                                             TipoDNI = pacientes.TipoDNI,
                                             EdadPac = (int)pacientes.EdadPac,
                                             Genero = (int)pacientes.Genero,
                                             IdUser = (int)pacientes.IdUser,
                                             Correo = pacientes.Correo,
                                             NumeroContacto = pacientes.NumeroContacto
                                         }).ToList();

                            Session["lista"] = listaPacs;
                        }
                    }
                    return View(listaPacs);
                }
            }
            catch (Exception ex)
            {
                return RedirectToAction("Error", "Home");
            }
        }

        public ActionResult TablaAuxiliar(PacientesCLS oPacientesCLS)
        {
            try
            {
                if (Session["UserID"] == null)
                {
                    return RedirectToAction("Login", "Login");
                }
                else
                {
                    string nombreUSR = oPacientesCLS.NombrePac;
                    llenarGenero();
                    GetTipoUsuarioList();
                    GetGeneroUsuarioList();
                    List<PacientesCLS> listaUsuario = new List<PacientesCLS>();
                    using (var db = new TurneroNewEntities())
                    {
                        if (oPacientesCLS.NombrePac == null)
                        {
                            listaUsuario = (from pacientes in db.Pacientes
                                            select new PacientesCLS
                                            {
                                                IdPaciente = pacientes.IdPaciente,
                                                NombrePac = pacientes.NombrePac,
                                                ApePac = pacientes.ApePac,
                                                DNIPac = pacientes.DNIPac,
                                                TipoDNI = pacientes.TipoDNI,
                                                EdadPac = pacientes.EdadPac,
                                                Genero = pacientes.Genero,

Views/Tablas/TablaAnalisis.cshtml
@model List<TurneroFaeracWeb.Models.IndiceAnalisisCLS>

<h2>Tabla Analisis</h2>



<h2 align="center">Listado de Analisis</h2>
<hr />

<!-- Button trigger modal -->
hr />

@using (Ajax.BeginForm("FiltrarA", "", new AjaxOptions
{
    HttpMethod = "Post",
    UpdateTargetId = "divRol",
    InsertionMode = InsertionMode.Replace
}, new { @id = "frmFiltrado" }))
{
    <div>
        @Html.Label("Filtrar por Nombre")
        @Html.TextBox("nombreFiltro")
    </div>
    <div id="divRol">
        @Html.Partial("_TablaAnalisis2", Model)
    </div>
}
<hr />

Views/Tablas/TablaAuxiliar.cshtml
@model List<TurneroFaeracWeb.Models.PacientesCLS>

<h2 align="center">Listado de Usuarios</h2>
<hr />

<!-- Button trigger modal -->
<button type="button" onclick="Agregar()" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
    Agregar
</button>
<hr />

@using (Ajax.BeginForm("FiltrarP", "", new AjaxOptions
{
    HttpMethod = "Post",
    UpdateTargetId = "divRol",
    InsertionMode = InsertionMode.Replace
}, new { @id = "frmFiltrado" }))
{
    @Html.Label("Filtrar por Apellido")
    @Html.TextBox("nombreFiltro")
    <div id="divRol">
        @Html.Partial("_TablaPacientes", Model)
    </div>
}
<hr />

<!-- Modal AGREGAR-->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title" id="exampleModalLabel" align="center" draggable="true"><b>ALTA-MODIFICAR User</b></h2>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            @using (Ajax.BeginForm("GuardarPacs", "Tablas", null, new AjaxOptions
            {
                HttpMethod = "POST",
                OnSuccess = "Guardar",
                InsertionMode = InsertionMode.Replace,
                UpdateTargetId = "divError"
            }))
            {
                @Html.Hidden("titulo")
        <div class="modal-body">
           
            <div>
                @Html.Label("Nombre")
                @Html.TextBox("NombrePac", null, new { @class = "form-control" })
            </div>
            <div>
                @Html.Label("Apellido")
                @Html.TextBox("ApePac", null, new { @class = "form-control" })
            </div>
            <div>
                @Html.Label("DNI")
                @Html.TextBox("DNIPac", null, new { @class = "form-control" })
            </div>
            <div>
                @Html.Label("Edad")
                @Html.TextBox("EdadPac", null, new { @class = "form-control" })
            </div>
            <div>
                <div class="mb-3">
                    <label>Genero</label>
                    <div class="mb-3">
                        <select class="form-select form-select-lg mb-3" aria-label=".form-select-lg example" id="Genero" name="Genero">
                            <option value="1">Masculino</option>
                            <option value="2">Femenino</option>
                            <option value="3">Otro</option>
                        </select>
                        <!-- Agrega un campo oculto para almacenar el valor seleccionado -->
                        <input type="hidden" id="IdGenero" name="IdGenero" />
                    </div>
                    <script>
                        // Agrega este script después de tu formulario
                        document.getElementById("Genero").addEventListener("change", function () {
                            var selectedValue = document.getElementById("Genero").value;
                            document.getElementById("IdGenero").value = selectedValue;
                        });
                    </script>
                </div>

                <div>
                    @Html.Label("IdUsuario")
                    @Html.TextBox("IdUser", null, new { @class = "form-control" })
                </div>
                <div>
                    @Html.Label("Correo")
                    @Html.TextBox("Correo", null, new { @class = "form-control" })
                </div>
                <div>
                    @Html.Label("Numero Tel")
                    @Html.TextBox("NumeroContacto", null, new { @class = "form-control" })
                </div>
              
            </div>


        </div>
                <div class="modal-footer">
                    <button type="button" id="btnclose" class="btn btn-secondary" data-dismiss="modal"><b>Cancelar</b></button>
                    <button type="submit" class="btn btn-primary"><b>GUARDAR</b></button>
                </div>
                <div id="divError" class="alert-warning"></div>
            }
        </div>
    </div>
</div>


<!-- Modal Eliminar -->
<div class="modal fade" id="EliminarConfirmacion" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog " role="document">
        <div class="modal-content">
            <div class="modal-header alert-danger">
                <h2 align="center" class="modal-title" id="exampleModalLabel"><b>Baja de Roles</b></h2>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <h4 align="center" class="modal-title alert-warning" id="exampleModalLabel"><b>¿Desea eliminar este ROL?</b></h4>
            <div class="modal-footer alert-warning">
                <button type="button" id="btnCerrar" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <button type="button" onclick="EliminarRegistro()" class="btn btn-primary">Aceptar</button>
            </div>
            <div id="divError"></div>
            }
        </div>
    </div>
</div>

Views/Tablas/TablaDoctores.cshtml
@model List<TurneroFaeracWeb.Models.DoctoresCLS>
@{
    ViewBag.Title = "listaEspecializacion";
}

<h2 align="center">Listado de Doctores</h2>
<hr />

<!-- Button trigger modal -->
<button type="button" onclick="Agregar()" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
    Agregar
</button>
<hr />

@using (Ajax.BeginForm("FiltrarD", "", new AjaxOptions
{
    HttpMethod = "Post",
    UpdateTargetId = "divRol",
    InsertionMode = InsertionMode.Replace
}, new { @id = "frmFiltrado" }))
{
    <div>
        @Html.Label("Filtrar por Nombre")
        @Html.TextBox("nombreFiltro")
    </div>
    <div id="divRol">
        @Html.Partial("_TablaDoctores", Model)
    </div>
}
<hr />

<!-- Modal AGREGAR-->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title" id="exampleModalLabel" align="center" draggable="true"><b>ALTA-MODIFICAR Doctor</b></h2>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            @using (Ajax.BeginForm("GuardarDocs", "Tablas", null, new AjaxOptions
            {
                HttpMethod = "POST",
                OnSuccess = "GuardarDocs",
                InsertionMode = InsertionMode.Replace,
                UpdateTargetId = "divError"
            }))
            {
                @Html.Hidden("titulo")
                <div class="modal-body">
                    <div>
                        @Html.Label("ID User")
                        @Html.TextBox("IdUser", null, new { @class = "form-control" })
                    </div>
                    <div>
                        @Html.Label("Nombre Doctor")
                        @Html.TextBox("NombreDoc", null, new { @class = "form-control" })
                    </div>
                    <div>
                        @Html.Label("Apellido Doctor")
                        @Html.TextBox("ApeDoc", null, new { @class = "form-control" })
                    </div>
                    <div class="mb-3">
                        <label>Especializacion</label>
                        <div class="mb-3">
                            <label>Especializaciones</label>
                            <select class="form-select form-select-lg mb-3" aria-label=".form-select-lg example" id="IDEspecializacion" name="IDEspecializacion">
                                <option value="1">Generalista</option>
                                <option value="2">Gastroenterologia</option>
                                <option value="3">Neurologia</option>
                                <option value="4">Cirujano</option>
                                <option value="5">Cuidados Paleativos</option>
                                <option value="6">Pediatra</option>
                                <option value="7">Ginecologo</option>
                                <option value="8">Otorrinolaringologo</option>
                                <option value="9">Oncologo</option>
                                <option value="10">Obstetra</option>
                                <option value="11">Proctologo</option>
                            </select>

                            <!-- Agrega un campo oculto para almacenar el valor seleccionado -->
                            <input type="hidden" id="IDEspecializacionHidden" name="IDEspecializacion" />

                            <script>
                                // Agrega este script después de tu formulario
                                document.getElementById("IDEspecializacion").addEventListener("change", function () {
                                    var selectedValue = document.getElementById("IDEspecializacion").value;
                                    document.getElementById("IDEspecializacionHidden").value = selectedValue;
                                });
                            </script>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" id="btnclose" class="btn btn-secondary" data-dismiss="modal"><b>Cancelar</b></button>
                    <button type="submit" class="btn btn-primary"><b>GUARDAR</b></button>
                </div>
                <div id="divError" class="alert-warning"></div>
            }
        </div>
    </div>
</div>

<!-- Modal Eliminar -->
<div class="modal fade" id="EliminarConfirmacion" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog " role="document">
        <div class="modal-content">
            <div class="modal-header alert-danger">
                <h2 align="center" class="modal-title" id="exampleModalLabel"><b>Baja de Roles</b></h2>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <h4 align="center" class="modal-title alert-warning" id="exampleModalLabel"><b>¿Desea eliminar este ROL?</b></h4>
            <div class="modal-footer alert-warning">
                <button type="button" id="btnCerrar" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <button type="button" onclick="Eliminard()" class="btn btn-primary">Aceptar</button>
            </div>
            <div id="divError"></div>
        </div>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    var frmFiltrado = document.getElementById("frmFiltrado");
    var nombreFiltro = document.getElementById("nombreFiltro");
    nombreFiltro.onkeyup = function () {
        $("#frmFiltrado").trigger("submit");
    }

    function AgregarD() {
        Limpiar();
        document.getElementById("divError").innerHTML = "";
        document.getElementById("titulo").value = "-1";
    }

    function GuardarDocs(resultado) {
        alert(resultado);
        if (resultado == "1" || resultado == "0") {
            $("#frmFiltrado").trigger("submit");
            document.getElementById("btnclose").click();
            alert("Se guardo correctamente");
        } else {
            if (resultado == "-1") {
                alert("Ese Doctor ya existe")
                document.getElementById("divError").innerHTML = "";
            } else
                alert("ERROR->No se pudo guardar el Doctor");
        }
    }

    function editard(id) {
        document.getElementById("divError").innerHTML = "";
        document.getElementById("titulo").value = id;

        $.get("../Tablas/RellenarDocs/?titulo=" + id, function (data) {
            document.getElementById("NombreDoc").value = data.NombreDoc;
            document.getElementById("ApeDoc").value = data.ApeDoc;
            document.getElementById("IDEspecializacion").value = data.IDEspecializacion;
   
            // Buscar el elemento select
            var generoSelect = document.getElementById("IDEspecializacion");

            // Iterar sobre las opciones y seleccionar la correspondiente al valor recibido
            for (var i = 0; i < generoSelect.options.length; i++) {
                if (generoSelect.options[i].value == data.IDEspecializacion) {
                    generoSelect.options[i].selected = true;
                    break;
                }
            }
        });
    }

    function Eliminar(IdDoc) {
        var id = document.getElementById("titulo").value = IdDoc;
    }

    function EliminarRegistro() {
        var id = document.getElementById("titulo").value;
        $.get("../Tablas/EliminarD/?IdDoc=" + id, function (data) {
            if (data == "1") {
                alert("Doctor Eliminado");
                $("#frmFiltrado").trigger("submit");
                document.getElementById("btnCerrar").click();
            }
        })
    }

    function Limpiar() {
        document.getElementById("NombreDoc").value = "";
        document.getElementById("ApeDoc").value = "";
        document.getElementById("IDEspecializacion").value = 0;
        document.getElementById("IdUser").value = 0;
        document.getElementById("divError").innerHTML = "";
    }
</script>

<script>
    $(document).ready(function () {
        $("#btnBuscar").click(function () {
            var selectedEspecializacion = $("#ddlEspecializacion").val();
            var nombreFiltro = $("#txtKeyword").val(); // Obtén el valor del filtro de búsqueda

            $.ajax({
                url: "/LandingPage/BuscarDocs",
                type: "POST",
                data: { idEspecializacion: selectedEspecializacion, nombreFiltro: nombreFiltro }, // Incluye ambos valores
                success: function (data) {
                    $("#resultadoBusqueda").html(data);
                },
                error: function () {
                    alert("Hubo un error al buscar doctores.");
                }
            });
        });
    });
</script>

<script>
    $(document).ready(function () {
        // Evento cuando se cambia la especialización
        $("#ddlEspecializacion").change(function () {
            var idEspecializacion = $(this).val();

            // Realiza una solicitud AJAX para obtener los doctores según la especialización seleccionada
            $.ajax({
                url: "/LandingPage/ObtenerDoctores", // Reemplaza con la URL correcta de tu acción
                type: "GET", // O POST según tu configuración
                data: { idEspecializacion: idEspecializacion },
                success: function (data) {
                    // Limpia el segundo select
                    $("#ddlDoctores").empty();

                    // Agrega las opciones de doctores
                    $.each(data, function (index, doctor) {
                        $("#ddlDoctores").append('<option value="' + doctor.Value + '">' + doctor.Text + '</option>');
                    });
                },
                error: function () {
                    alert("Hubo un error al cargar los doctores.");
                }
            });
        });
    });
</script>

Views/Tablas/_TablaAnalisis.cshtml
@model List<TurneroFaeracWeb.Models.IndiceAnalisisCLS>
@{
    ViewBag.Title = "listaEspecializacion";
}

<table class="table tab-content table-bordered table-hover">
    <tr>
        <td align="center"><strong>ID Paciente</strong></td>
        <td align="center"><strong>ID Analisis</strong></td>
        <td align="center"><strong>Fecha Analisis</strong></td>
        <td align="center"><strong>Link Analisis</strong></td>
        <td align="center"><strong>Especializacion</strong></td>
        <td align="center"><strong>Acciones</strong></td>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td style="text-align: center;">
                @Html.DisplayFor(modelItem => item.IdPaciente)
            </td>
            <td style="text-align: center;">
                @Html.DisplayFor(modelItem => item.IdAnalisis)
            </td>
            <td style="text-align: center;">
                @Html.DisplayFor(modelItem => item.FechaAnalisis)
            </td>
            <td style="text-align: center;">
                @Html.DisplayFor(modelItem => item.LinkAnalisis)
            </td>


        </tr>
    }
</table>

Views/Tablas/_TablaAnalisis2.cshtml
@model List<TurneroFaeracWeb.Models.IndiceAnalisisCLS>


<table class="table tab-content table-bordered table-hover">
    <tr>
        <td align="center"><strong>Paciente</strong></td>
        <td align="center"><strong>IdAnalisis</strong></td>
        <td align="center"><strong>Fecha Analisis</strong></td>
        <td align="center"><strong>Analisis</strong></td>

    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td style="text-align: center;">
                @Html.DisplayFor(modelItem => item.IdPaciente)
            </td>
            <td style="text-align: center;">
                @Html.DisplayFor(modelItem => item.IdAnalisis)
            </td>
            <td style="text-align: center;">
                @Html.DisplayFor(modelItem => item.FechaAnalisis)
            </td>
            <td style="text-align: center;">
                @Html.DisplayFor(modelItem => item.LinkAnalisis)
            </td>


        </tr>
    }
</table>

Views/Tablas/_TablaTurnos.cshtml
@model List<TurneroFaeracWeb.Models.TablaTurnosCLS>
@{
    ViewBag.Lista = "listaEspecializacion";
}

<table class="table tab-content table-bordered table-hover">
    <tr>
        <td align="center"><strong>ID Turno</strong></td>
        <td align="center"><strong>ID Paciente</strong></td>
        <td align="center"><strong>ID Doctor</strong></td>
        <td align="center"><strong>Inicio</strong></td>
        <!-- Agrega otras columnas según sea necesario -->
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td style="text-align: center;">
                @Html.DisplayFor(modelItem => item.IdTurno)
            </td>
            <td style="text-align: center;">
                @Html.DisplayFor(modelItem => item.IdPaciente)
            </td>
            <td style="text-align: center;">
                @Html.DisplayFor(modelItem => item.IdDoc)
            </td>
            <td style="text-align: center;">
                @Html.DisplayFor(modelItem => item.inicio)
            </td>
            <td style="text-align: center;">
                <button type="button" onclick="editarp(@item.IdPaciente)" class="btn btn-primary glyphicon-edit" data-toggle="modal" data-target="#exampleModal">
                    <img src="~/images/btnedit.png" alt="editar" class="editar-icon" />
                </button>
                <button type="button" onclick="Eliminar(@item.IdPaciente)" class="btn btn-danger glyphicon-trash" data-toggle="modal" data-target="#EliminarConfirmacion">
                    <img src="~/images/btnborrar.png" alt="Eliminar" class="icon" />
                </button>
            </td>
        </tr>

    }
</table>